on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      # Ставим зависимости
      - run: npm install
      # Запускаем линтер
      - run: npx eslint .
      # Запускаем jest
      - name: Test & publish code coverag
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: npm run test
          debug: true